// Static team profiles for all 48 WC2026 participants.
// Confederation, ranking, WC record, coach, brief history, key squad members.

export interface PlayerInfo {
  name: string;
  pos: "GK" | "DF" | "MF" | "FW";
  club: string;
  caps: number;
  goals: number;
  age: number;
  number?: number;
}

export interface TeamProfile {
  name: string;
  code: string;
  confederation: string;
  fifaRanking: number;
  wcAppearances: number;
  bestFinish: string;
  coach: string;
  nickname: string;
  kitColors: { primary: string; secondary: string };
  history: string;
  squad: PlayerInfo[];
}

export const TEAM_PROFILES: Record<string, TeamProfile> = {
  "Mexico": {
    name: "Mexico", code: "MEX", confederation: "CONCACAF", fifaRanking: 15,
    wcAppearances: 17, bestFinish: "Quarter-finals (1970, 1986)", coach: "Javier Aguirre",
    nickname: "El Tri", kitColors: { primary: "#006847", secondary: "#CE1126" },
    history: "Mexico are co-hosts and have qualified for every World Cup since 1994. They have historically struggled to advance past the Round of 16 — a barrier known as the 'Quinto Partido' curse. On home soil in 1970 and 1986, they reached the quarter-finals, their best results.",
    squad: [
      { name: "Guillermo Ochoa", pos: "GK", club: "Club América", caps: 140, goals: 0, age: 41, number: 13 },
      { name: "Jorge Sánchez", pos: "DF", club: "Porto", caps: 35, goals: 2, age: 28, number: 2 },
      { name: "César Montes", pos: "DF", club: "Almería", caps: 55, goals: 3, age: 27, number: 3 },
      { name: "Edson Álvarez", pos: "MF", club: "West Ham", caps: 70, goals: 3, age: 28, number: 4 },
      { name: "Luis Chávez", pos: "MF", club: "Pachuca", caps: 30, goals: 5, age: 29, number: 14 },
      { name: "Hirving Lozano", pos: "FW", club: "San Diego FC", caps: 65, goals: 17, age: 30, number: 22 },
      { name: "Raúl Jiménez", pos: "FW", club: "Fulham", caps: 105, goals: 33, age: 35, number: 9 },
      { name: "Santiago Giménez", pos: "FW", club: "Feyenoord", caps: 25, goals: 12, age: 25, number: 19 },
    ],
  },
  "South Africa": {
    name: "South Africa", code: "RSA", confederation: "CAF", fifaRanking: 59,
    wcAppearances: 4, bestFinish: "Group stage (1998, 2002, 2010)", coach: "Hugo Broos",
    nickname: "Bafana Bafana", kitColors: { primary: "#FFB81C", secondary: "#007749" },
    history: "South Africa made history as the first African nation to host the World Cup in 2010 but have never advanced past the group stage. Under Hugo Broos, they won the 2023 AFCON bronze medal and qualified for their first World Cup since hosting, signaling a revival.",
    squad: [
      { name: "Ronwen Williams", pos: "GK", club: "Mamelodi Sundowns", caps: 45, goals: 0, age: 32, number: 1 },
      { name: "Mothobi Mvala", pos: "DF", club: "Mamelodi Sundowns", caps: 30, goals: 2, age: 30, number: 5 },
      { name: "Teboho Mokoena", pos: "MF", club: "Mamelodi Sundowns", caps: 35, goals: 6, age: 27, number: 8 },
      { name: "Percy Tau", pos: "FW", club: "Al Ahly", caps: 50, goals: 15, age: 32, number: 11 },
      { name: "Themba Zwane", pos: "MF", club: "Mamelodi Sundowns", caps: 40, goals: 10, age: 35, number: 10 },
    ],
  },
  "South Korea": {
    name: "South Korea", code: "KOR", confederation: "AFC", fifaRanking: 23,
    wcAppearances: 11, bestFinish: "Semi-finals (2002)", coach: "Hong Myung-bo",
    nickname: "Taegeuk Warriors", kitColors: { primary: "#C60C30", secondary: "#003478" },
    history: "South Korea co-hosted the 2002 World Cup and stunned the world by reaching the semi-finals, defeating Spain and Italy along the way. They are Asia's most consistent World Cup performers with 11 appearances. Son Heung-min leads a golden generation.",
    squad: [
      { name: "Kim Seung-gyu", pos: "GK", club: "Al-Shabab", caps: 60, goals: 0, age: 36, number: 1 },
      { name: "Kim Min-jae", pos: "DF", club: "Bayern Munich", caps: 55, goals: 3, age: 29, number: 3 },
      { name: "Lee Kang-in", pos: "MF", club: "PSG", caps: 50, goals: 12, age: 25, number: 10 },
      { name: "Hwang Hee-chan", pos: "FW", club: "Wolverhampton", caps: 55, goals: 14, age: 30, number: 11 },
      { name: "Son Heung-min", pos: "FW", club: "Tottenham", caps: 120, goals: 40, age: 33, number: 7 },
      { name: "Cho Gue-sung", pos: "FW", club: "Midtjylland", caps: 25, goals: 10, age: 28, number: 9 },
    ],
  },
  "Czechia": {
    name: "Czechia", code: "CZE", confederation: "UEFA", fifaRanking: 36,
    wcAppearances: 7, bestFinish: "Runner-up (1934, 1962 as Czechoslovakia)", coach: "Ivan Hašek",
    nickname: "Czech Lions", kitColors: { primary: "#D7141A", secondary: "#11457E" },
    history: "Czechia (formerly Czechoslovakia) have a proud football history including two World Cup finals and the 1976 European Championship. As an independent nation since 1993, they reached the 2006 World Cup and were Euro 2004 semi-finalists. This is their first World Cup in 20 years.",
    squad: [
      { name: "Jindřich Staněk", pos: "GK", club: "Slavia Prague", caps: 15, goals: 0, age: 30, number: 1 },
      { name: "Tomáš Souček", pos: "MF", club: "West Ham", caps: 65, goals: 12, age: 31, number: 6 },
      { name: "Vladimír Coufal", pos: "DF", club: "West Ham", caps: 40, goals: 1, age: 33, number: 5 },
      { name: "Patrik Schick", pos: "FW", club: "Bayer Leverkusen", caps: 45, goals: 20, age: 30, number: 10 },
      { name: "Adam Hložek", pos: "FW", club: "Bayer Leverkusen", caps: 35, goals: 8, age: 24, number: 17 },
    ],
  },
  "Canada": {
    name: "Canada", code: "CAN", confederation: "CONCACAF", fifaRanking: 43,
    wcAppearances: 3, bestFinish: "Group stage (1986, 2022)", coach: "Jesse Marsch",
    nickname: "Les Rouges", kitColors: { primary: "#FF0000", secondary: "#FFFFFF" },
    history: "Canada are co-hosts and returned to the World Cup in 2022 after a 36-year absence. Led by Alphonso Davies and Jonathan David, they've become a rising force in CONCACAF. As hosts, they'll look to build on 2022's experience and make a deep run on home soil.",
    squad: [
      { name: "Milan Borjan", pos: "GK", club: "Red Star Belgrade", caps: 75, goals: 0, age: 38, number: 18 },
      { name: "Alphonso Davies", pos: "DF", club: "Real Madrid", caps: 55, goals: 15, age: 25, number: 19 },
      { name: "Tajon Buchanan", pos: "MF", club: "Inter Milan", caps: 40, goals: 8, age: 27, number: 11 },
      { name: "Stephen Eustáquio", pos: "MF", club: "Porto", caps: 45, goals: 3, age: 28, number: 7 },
      { name: "Jonathan David", pos: "FW", club: "Arsenal", caps: 55, goals: 28, age: 26, number: 20 },
      { name: "Cyle Larin", pos: "FW", club: "Real Valladolid", caps: 65, goals: 30, age: 29, number: 17 },
    ],
  },
  "Bosnia & Herzegovina": {
    name: "Bosnia & Herzegovina", code: "BIH", confederation: "UEFA", fifaRanking: 57,
    wcAppearances: 2, bestFinish: "Group stage (2014)", coach: "Sergej Barbarez",
    nickname: "Dragons", kitColors: { primary: "#002395", secondary: "#FECB00" },
    history: "Bosnia & Herzegovina qualified for their first World Cup in 2014 in Brazil, a huge achievement for the young nation. Led by Edin Džeko's generation, they showed they could compete at the highest level. They return to the World Cup stage for the first time in 12 years.",
    squad: [
      { name: "Nikola Vasilj", pos: "GK", club: "St. Pauli", caps: 30, goals: 0, age: 28, number: 12 },
      { name: "Sead Kolašinac", pos: "DF", club: "Atalanta", caps: 50, goals: 2, age: 33, number: 3 },
      { name: "Edin Džeko", pos: "FW", club: "Fenerbahçe", caps: 135, goals: 65, age: 40, number: 11 },
      { name: "Miralem Pjanić", pos: "MF", club: "Sharjah FC", caps: 110, goals: 15, age: 36, number: 8 },
      { name: "Ermedin Demirović", pos: "FW", club: "Stuttgart", caps: 30, goals: 10, age: 26, number: 9 },
    ],
  },
  "Qatar": {
    name: "Qatar", code: "QAT", confederation: "AFC", fifaRanking: 42,
    wcAppearances: 2, bestFinish: "Group stage (2022)", coach: "Marquez López",
    nickname: "The Maroons", kitColors: { primary: "#8A1538", secondary: "#FFFFFF" },
    history: "Qatar hosted the 2022 World Cup — the first Middle Eastern nation to do so — but became the first host to lose all three group matches. Two-time Asian Cup champions (2019, 2023), they've shown quality at continental level and return to the World Cup with a point to prove.",
    squad: [
      { name: "Saad Al-Sheeb", pos: "GK", club: "Al-Sadd", caps: 90, goals: 0, age: 36, number: 1 },
      { name: "Hassan Al-Haydos", pos: "MF", club: "Al-Sadd", caps: 185, goals: 40, age: 35, number: 10 },
      { name: "Akram Afif", pos: "FW", club: "Al-Sadd", caps: 90, goals: 40, age: 27, number: 11 },
      { name: "Almoez Ali", pos: "FW", club: "Al-Duhail", caps: 100, goals: 50, age: 28, number: 19 },
    ],
  },
  "Switzerland": {
    name: "Switzerland", code: "SUI", confederation: "UEFA", fifaRanking: 19,
    wcAppearances: 12, bestFinish: "Quarter-finals (1934, 1938, 1954)", coach: "Murat Yakın",
    nickname: "Nati", kitColors: { primary: "#FF0000", secondary: "#FFFFFF" },
    history: "Switzerland are a model of consistency, qualifying for five consecutive World Cups. They reached the Euro 2020 quarter-finals after eliminating France on penalties. Granit Xhaka anchors a midfield that combines tactical discipline with technical quality.",
    squad: [
      { name: "Yann Sommer", pos: "GK", club: "Inter Milan", caps: 90, goals: 0, age: 37, number: 1 },
      { name: "Manuel Akanji", pos: "DF", club: "Manchester City", caps: 60, goals: 3, age: 30, number: 5 },
      { name: "Granit Xhaka", pos: "MF", club: "Bayer Leverkusen", caps: 130, goals: 14, age: 33, number: 10 },
      { name: "Dan Ndoye", pos: "FW", club: "Bologna", caps: 20, goals: 3, age: 25, number: 23 },
      { name: "Breel Embolo", pos: "FW", club: "Monaco", caps: 65, goals: 14, age: 29, number: 7 },
      { name: "Noah Okafor", pos: "FW", club: "AC Milan", caps: 25, goals: 6, age: 25, number: 17 },
    ],
  },
  "Brazil": {
    name: "Brazil", code: "BRA", confederation: "CONMEBOL", fifaRanking: 5,
    wcAppearances: 23, bestFinish: "Champions (1958, 1962, 1970, 1994, 2002)", coach: "Dorival Júnior",
    nickname: "Seleção", kitColors: { primary: "#FFDF00", secondary: "#009739" },
    history: "Brazil are the most successful World Cup nation with five titles and the only team to have appeared in every tournament. The samba style defined by Pelé, Ronaldo, Ronaldinho, and now Vinícius Jr has made them football's most iconic nation. They haven't won since 2002 but remain perennial contenders.",
    squad: [
      { name: "Alisson", pos: "GK", club: "Liverpool", caps: 70, goals: 0, age: 33, number: 1 },
      { name: "Marquinhos", pos: "DF", club: "PSG", caps: 80, goals: 6, age: 32, number: 4 },
      { name: "Éder Militão", pos: "DF", club: "Real Madrid", caps: 35, goals: 2, age: 28, number: 14 },
      { name: "Casemiro", pos: "MF", club: "Manchester United", caps: 75, goals: 7, age: 34, number: 5 },
      { name: "Rodrygo", pos: "FW", club: "Real Madrid", caps: 30, goals: 7, age: 25, number: 21 },
      { name: "Vinícius Jr", pos: "FW", club: "Real Madrid", caps: 35, goals: 8, age: 26, number: 7 },
      { name: "Endrick", pos: "FW", club: "Real Madrid", caps: 15, goals: 5, age: 20, number: 9 },
    ],
  },
  "Morocco": {
    name: "Morocco", code: "MAR", confederation: "CAF", fifaRanking: 13,
    wcAppearances: 7, bestFinish: "Semi-finals (2022)", coach: "Walid Regragui",
    nickname: "Atlas Lions", kitColors: { primary: "#C1272D", secondary: "#006233" },
    history: "Morocco made history at the 2022 World Cup as the first African and Arab nation to reach the semi-finals, defeating Belgium, Spain, and Portugal. Their defensive solidity and passionate support captured hearts worldwide. They arrive as one of the genuine dark horses.",
    squad: [
      { name: "Yassine Bounou", pos: "GK", club: "Al-Hilal", caps: 60, goals: 0, age: 33, number: 1 },
      { name: "Achraf Hakimi", pos: "DF", club: "PSG", caps: 75, goals: 12, age: 27, number: 2 },
      { name: "Nayef Aguerd", pos: "DF", club: "West Ham", caps: 40, goals: 3, age: 30, number: 5 },
      { name: "Sofyan Amrabat", pos: "MF", club: "Fiorentina", caps: 60, goals: 1, age: 30, number: 4 },
      { name: "Hakim Ziyech", pos: "MF", club: "Galatasaray", caps: 50, goals: 20, age: 33, number: 7 },
      { name: "Youssef En-Nesyri", pos: "FW", club: "Fenerbahçe", caps: 70, goals: 20, age: 29, number: 19 },
    ],
  },
  "Haiti": {
    name: "Haiti", code: "HAI", confederation: "CONCACAF", fifaRanking: 90,
    wcAppearances: 2, bestFinish: "Group stage (1974)", coach: "Marc Collat",
    nickname: "Les Grenadiers", kitColors: { primary: "#00209F", secondary: "#D21034" },
    history: "Haiti return to the World Cup for the first time since 1974, when Emmanuel Sanon scored against Italy and ended Dino Zoff's record unbeaten run. This qualification is a triumph for Caribbean football and a nation that has overcome immense challenges. They bring passionate support and fearless energy.",
    squad: [
      { name: "Josué Duverger", pos: "GK", club: "Grenoble", caps: 20, goals: 0, age: 26, number: 1 },
      { name: "Carlens Arcus", pos: "DF", club: "STVV", caps: 25, goals: 1, age: 26, number: 4 },
      { name: "Derrick Etienne Jr", pos: "MF", club: "Columbus Crew", caps: 35, goals: 5, age: 28, number: 10 },
      { name: "Frantzdy Pierrot", pos: "FW", club: "Goztepe", caps: 30, goals: 12, age: 31, number: 9 },
    ],
  },
  "Scotland": {
    name: "Scotland", code: "SCO", confederation: "UEFA", fifaRanking: 39,
    wcAppearances: 9, bestFinish: "Group stage (1954–1998)", coach: "Steve Clarke",
    nickname: "Tartan Army", kitColors: { primary: "#003399", secondary: "#FFFFFF" },
    history: "Scotland have the dubious honor of being the team with the most World Cup appearances without ever advancing from the group stage. The Tartan Army is one of football's most beloved supporter bases. Under Steve Clarke, they qualified for Euro 2020 and 2024, and now return to the World Cup after 28 years.",
    squad: [
      { name: "Angus Gunn", pos: "GK", club: "Norwich", caps: 15, goals: 0, age: 30, number: 1 },
      { name: "Andrew Robertson", pos: "DF", club: "Liverpool", caps: 75, goals: 3, age: 32, number: 3 },
      { name: "Kieran Tierney", pos: "DF", club: "Real Sociedad", caps: 45, goals: 1, age: 29, number: 2 },
      { name: "Scott McTominay", pos: "MF", club: "Napoli", caps: 55, goals: 12, age: 29, number: 6 },
      { name: "John McGinn", pos: "MF", club: "Aston Villa", caps: 65, goals: 18, age: 31, number: 7 },
      { name: "Che Adams", pos: "FW", club: "Torino", caps: 30, goals: 6, age: 30, number: 10 },
    ],
  },
  "United States": {
    name: "United States", code: "USA", confederation: "CONCACAF", fifaRanking: 11,
    wcAppearances: 12, bestFinish: "Semi-finals (1930); Quarter-finals (2002)", coach: "Mauricio Pochettino",
    nickname: "USMNT", kitColors: { primary: "#FFFFFF", secondary: "#002868" },
    history: "The United States co-host for the second time after 1994 and aim to capitalize on home advantage. Their young core — Pulisic, McKennie, Reyna, Musah — gained experience in 2022. American soccer's growth makes this tournament a pivotal moment for the sport domestically.",
    squad: [
      { name: "Matt Turner", pos: "GK", club: "Crystal Palace", caps: 35, goals: 0, age: 32, number: 1 },
      { name: "Sergiño Dest", pos: "DF", club: "PSV", caps: 35, goals: 2, age: 25, number: 2 },
      { name: "Weston McKennie", pos: "MF", club: "Juventus", caps: 55, goals: 10, age: 27, number: 8 },
      { name: "Yunus Musah", pos: "MF", club: "AC Milan", caps: 40, goals: 1, age: 23, number: 6 },
      { name: "Christian Pulisic", pos: "FW", club: "AC Milan", caps: 70, goals: 30, age: 27, number: 10 },
      { name: "Giovanni Reyna", pos: "FW", club: "Borussia Dortmund", caps: 30, goals: 5, age: 23, number: 7 },
      { name: "Folarin Balogun", pos: "FW", club: "Monaco", caps: 20, goals: 6, age: 25, number: 20 },
    ],
  },
  "Paraguay": {
    name: "Paraguay", code: "PAR", confederation: "CONMEBOL", fifaRanking: 55,
    wcAppearances: 9, bestFinish: "Quarter-finals (2010)", coach: "Alfredo Moreno",
    nickname: "La Albirroja", kitColors: { primary: "#FFFFFF", secondary: "#DA291C" },
    history: "Paraguay reached the quarter-finals in 2010, their best result, after a run built on defensive resilience and goalkeeper Justo Villar's heroics. They missed the 2014, 2018, and 2022 World Cups but return with renewed hunger. A new generation is eager to write the next chapter.",
    squad: [
      { name: "Antony Silva", pos: "GK", club: "Cerro Porteño", caps: 40, goals: 0, age: 32, number: 1 },
      { name: "Gustavo Gómez", pos: "DF", club: "Palmeiras", caps: 80, goals: 8, age: 33, number: 3 },
      { name: "Miguel Almirón", pos: "MF", club: "Newcastle", caps: 60, goals: 10, age: 32, number: 10 },
      { name: "Julio Enciso", pos: "FW", club: "Brighton", caps: 20, goals: 4, age: 21, number: 17 },
    ],
  },
  "Australia": {
    name: "Australia", code: "AUS", confederation: "AFC", fifaRanking: 24,
    wcAppearances: 7, bestFinish: "Round of 16 (2006, 2022)", coach: "Tony Popovic",
    nickname: "Socceroos", kitColors: { primary: "#FFCD00", secondary: "#008751" },
    history: "Australia surprised everyone in 2022 by reaching the Round of 16 for the first time since 2006, galvanizing the sport in a country dominated by other football codes. The Socceroos bring a fearless mentality and a growing pool of talent playing in Europe's top leagues.",
    squad: [
      { name: "Mathew Ryan", pos: "GK", club: "Roma", caps: 90, goals: 0, age: 34, number: 1 },
      { name: "Harry Souttar", pos: "DF", club: "Leicester", caps: 25, goals: 5, age: 27, number: 6 },
      { name: "Riley McGree", pos: "MF", club: "Middlesbrough", caps: 25, goals: 4, age: 25, number: 13 },
      { name: "Jackson Irvine", pos: "MF", club: "St. Pauli", caps: 65, goals: 8, age: 32, number: 7 },
      { name: "Craig Goodwin", pos: "FW", club: "Al-Wehda", caps: 25, goals: 5, age: 33, number: 11 },
    ],
  },
  "Türkiye": {
    name: "Türkiye", code: "TUR", confederation: "UEFA", fifaRanking: 26,
    wcAppearances: 3, bestFinish: "Semi-finals (2002)", coach: "Vincenzo Montella",
    nickname: "Crescent Stars", kitColors: { primary: "#E30A17", secondary: "#FFFFFF" },
    history: "Türkiye stunned the world in 2002 by finishing third on their World Cup debut in the modern era, with Hakan Şükür scoring the fastest World Cup goal (11 seconds). After missing three consecutive tournaments, they return with a vibrant young generation led by Arda Güler and Kenan Yıldız.",
    squad: [
      { name: "Altay Bayındır", pos: "GK", club: "Manchester United", caps: 15, goals: 0, age: 28, number: 1 },
      { name: "Ferdi Kadıoğlu", pos: "DF", club: "Brighton", caps: 25, goals: 1, age: 25, number: 2 },
      { name: "Hakan Çalhanoğlu", pos: "MF", club: "Inter Milan", caps: 90, goals: 20, age: 32, number: 10 },
      { name: "Arda Güler", pos: "MF", club: "Real Madrid", caps: 15, goals: 5, age: 21, number: 8 },
      { name: "Kenan Yıldız", pos: "FW", club: "Juventus", caps: 15, goals: 3, age: 21, number: 18 },
    ],
  },
  "Germany": {
    name: "Germany", code: "GER", confederation: "UEFA", fifaRanking: 3,
    wcAppearances: 21, bestFinish: "Champions (1954, 1974, 1990, 2014)", coach: "Julian Nagelsmann",
    nickname: "Die Mannschaft", kitColors: { primary: "#FFFFFF", secondary: "#000000" },
    history: "Four-time champions Germany are one of football's superpowers. After group-stage exits in 2018 and 2022, Julian Nagelsmann has rejuvenated the squad. Jamal Musiala and Florian Wirtz lead an exciting new era. Germany showed at Euro 2024 on home soil that they're back among the elite.",
    squad: [
      { name: "Manuel Neuer", pos: "GK", club: "Bayern Munich", caps: 120, goals: 0, age: 40, number: 1 },
      { name: "Antonio Rüdiger", pos: "DF", club: "Real Madrid", caps: 70, goals: 3, age: 33, number: 2 },
      { name: "Joshua Kimmich", pos: "MF", club: "Bayern Munich", caps: 95, goals: 6, age: 31, number: 6 },
      { name: "Jamal Musiala", pos: "MF", club: "Bayern Munich", caps: 40, goals: 8, age: 23, number: 10 },
      { name: "Florian Wirtz", pos: "MF", club: "Bayer Leverkusen", caps: 30, goals: 10, age: 23, number: 17 },
      { name: "Kai Havertz", pos: "FW", club: "Arsenal", caps: 55, goals: 20, age: 27, number: 7 },
    ],
  },
  "Curaçao": {
    name: "Curaçao", code: "CUW", confederation: "CONCACAF", fifaRanking: 85,
    wcAppearances: 1, bestFinish: "Debut (2026)", coach: "Dick Advocaat",
    nickname: "Team Curaçao", kitColors: { primary: "#003DA5", secondary: "#FFCD00" },
    history: "Curaçao make their World Cup debut — a remarkable achievement for the small Caribbean island of 150,000 people. Several players of Curaçaoan descent chose to represent their heritage over the Netherlands, giving the team surprising quality. This is the ultimate underdog story.",
    squad: [
      { name: "Eloy Room", pos: "GK", club: "PSV", caps: 30, goals: 0, age: 37, number: 1 },
      { name: "Cuco Martina", pos: "DF", club: "Jong PSV", caps: 40, goals: 2, age: 37, number: 2 },
      { name: "Juninho Bacuna", pos: "MF", club: "Birmingham", caps: 25, goals: 5, age: 29, number: 8 },
      { name: "Jairzinho Pieter", pos: "FW", club: "Venlo", caps: 20, goals: 6, age: 26, number: 9 },
    ],
  },
  "Ivory Coast": {
    name: "Ivory Coast", code: "CIV", confederation: "CAF", fifaRanking: 38,
    wcAppearances: 4, bestFinish: "Group stage (2006–2014)", coach: "Emerse Faé",
    nickname: "Elephants", kitColors: { primary: "#FF8200", secondary: "#009739" },
    history: "Ivory Coast won the 2023 Africa Cup of Nations on home soil — their third title. Despite a golden generation featuring Drogba, Touré, and Kalou, they never progressed past the group stage at the World Cup. The current squad, led by Sébastien Haller, aims to break that ceiling.",
    squad: [
      { name: "Badra Ali Sangaré", pos: "GK", club: "Augsburg", caps: 10, goals: 0, age: 26, number: 1 },
      { name: "Serge Aurier", pos: "DF", club: "Free Agent", caps: 75, goals: 4, age: 33, number: 2 },
      { name: "Franck Kessié", pos: "MF", club: "Al-Ahli", caps: 70, goals: 8, age: 29, number: 8 },
      { name: "Simon Adingra", pos: "FW", club: "Brighton", caps: 20, goals: 5, age: 22, number: 7 },
      { name: "Sébastien Haller", pos: "FW", club: "Borussia Dortmund", caps: 30, goals: 10, age: 32, number: 9 },
    ],
  },
  "Ecuador": {
    name: "Ecuador", code: "ECU", confederation: "CONMEBOL", fifaRanking: 28,
    wcAppearances: 5, bestFinish: "Round of 16 (2006)", coach: "Sebastián Beccacece",
    nickname: "La Tri", kitColors: { primary: "#FFD100", secondary: "#003DA5" },
    history: "Ecuador have established themselves as a consistent CONMEBOL qualifier with appearances in 2002, 2006, 2014, and 2022. They reached the Round of 16 in 2006 with a squad anchored in altitude-adapted fitness. Moisés Caicedo leads a young, dynamic midfield.",
    squad: [
      { name: "Alexander Domínguez", pos: "GK", club: "Liga de Quito", caps: 50, goals: 0, age: 38, number: 22 },
      { name: "Piero Hincapié", pos: "DF", club: "Bayer Leverkusen", caps: 35, goals: 1, age: 23, number: 3 },
      { name: "Moisés Caicedo", pos: "MF", club: "Chelsea", caps: 40, goals: 3, age: 24, number: 23 },
      { name: "Enner Valencia", pos: "FW", club: "Internacional", caps: 80, goals: 40, age: 36, number: 13 },
      { name: "Kendry Páez", pos: "MF", club: "Chelsea", caps: 10, goals: 2, age: 18, number: 8 },
    ],
  },
  "Netherlands": {
    name: "Netherlands", code: "NED", confederation: "UEFA", fifaRanking: 7,
    wcAppearances: 11, bestFinish: "Runner-up (1974, 1978, 2010)", coach: "Ronald Koeman",
    nickname: "Oranje", kitColors: { primary: "#FF6600", secondary: "#FFFFFF" },
    history: "The Netherlands have been the best team never to win the World Cup, finishing as runners-up three times. Total Football, invented by Cruyff and Michels, changed the sport forever. Under Koeman, they reached the 2022 quarter-finals and remain a force with a blend of experience and youth.",
    squad: [
      { name: "Bart Verbruggen", pos: "GK", club: "Brighton", caps: 15, goals: 0, age: 23, number: 1 },
      { name: "Virgil van Dijk", pos: "DF", club: "Liverpool", caps: 70, goals: 8, age: 35, number: 4 },
      { name: "Frenkie de Jong", pos: "MF", club: "Barcelona", caps: 55, goals: 2, age: 29, number: 21 },
      { name: "Xavi Simons", pos: "MF", club: "RB Leipzig", caps: 20, goals: 4, age: 23, number: 10 },
      { name: "Memphis Depay", pos: "FW", club: "Free Agent", caps: 95, goals: 46, age: 32, number: 10 },
      { name: "Cody Gakpo", pos: "FW", club: "Liverpool", caps: 40, goals: 14, age: 27, number: 11 },
    ],
  },
  "Japan": {
    name: "Japan", code: "JPN", confederation: "AFC", fifaRanking: 14,
    wcAppearances: 8, bestFinish: "Round of 16 (2002, 2010, 2018, 2022)", coach: "Hajime Moriyasu",
    nickname: "Samurai Blue", kitColors: { primary: "#003DA5", secondary: "#FFFFFF" },
    history: "Japan have become Asia's most feared World Cup side, beating Germany and Spain in 2022's group stage. With an unprecedented number of players in Europe's top leagues, they're no longer underdogs. Moriyasu's organized pressing and rapid transitions make them dangerous against anyone.",
    squad: [
      { name: "Zion Suzuki", pos: "GK", club: "Parma", caps: 10, goals: 0, age: 22, number: 12 },
      { name: "Takehiro Tomiyasu", pos: "DF", club: "Arsenal", caps: 40, goals: 1, age: 27, number: 2 },
      { name: "Ko Itakura", pos: "DF", club: "Borussia M'gladbach", caps: 30, goals: 2, age: 29, number: 4 },
      { name: "Wataru Endō", pos: "MF", club: "Liverpool", caps: 60, goals: 4, age: 33, number: 6 },
      { name: "Takefusa Kubo", pos: "FW", club: "Real Sociedad", caps: 30, goals: 5, age: 25, number: 11 },
      { name: "Kaoru Mitoma", pos: "FW", club: "Brighton", caps: 30, goals: 5, age: 29, number: 8 },
    ],
  },
  "Sweden": {
    name: "Sweden", code: "SWE", confederation: "UEFA", fifaRanking: 33,
    wcAppearances: 13, bestFinish: "Runner-up (1958)", coach: "Jon Dahl Tomasson",
    nickname: "Blågult", kitColors: { primary: "#FECC02", secondary: "#006AA7" },
    history: "Sweden reached the 1958 World Cup final on home soil and finished third in 1994 behind the lethal strike partnership of Brolin and Dahlin. The post-Zlatan era has proven the team is more than one man — they reached the 2018 quarter-finals and Euro 2020 Round of 16.",
    squad: [
      { name: "Robin Olsen", pos: "GK", club: "Aston Villa", caps: 55, goals: 0, age: 36, number: 1 },
      { name: "Victor Lindelöf", pos: "DF", club: "Manchester United", caps: 60, goals: 2, age: 31, number: 3 },
      { name: "Alexander Isak", pos: "FW", club: "Newcastle", caps: 40, goals: 14, age: 26, number: 11 },
      { name: "Dejan Kulusevski", pos: "FW", club: "Tottenham", caps: 40, goals: 8, age: 26, number: 21 },
      { name: "Viktor Gyökeres", pos: "FW", club: "Sporting CP", caps: 25, goals: 15, age: 28, number: 9 },
    ],
  },
  "Tunisia": {
    name: "Tunisia", code: "TUN", confederation: "CAF", fifaRanking: 37,
    wcAppearances: 7, bestFinish: "Group stage (1978–2022)", coach: "Faouzi Benzarti",
    nickname: "Eagles of Carthage", kitColors: { primary: "#CE1126", secondary: "#FFFFFF" },
    history: "Tunisia were the first African team to win a World Cup match (1978 vs Mexico). They've qualified for six of the last seven tournaments but have never escaped the group stage. A strong defensive identity and tactical discipline make them difficult opponents for anyone.",
    squad: [
      { name: "Aymen Dahmen", pos: "GK", club: "Montpellier", caps: 20, goals: 0, age: 26, number: 1 },
      { name: "Montassar Talbi", pos: "DF", club: "Lorient", caps: 35, goals: 3, age: 28, number: 6 },
      { name: "Aïssa Laïdouni", pos: "MF", club: "Union Berlin", caps: 30, goals: 2, age: 28, number: 14 },
      { name: "Wahbi Khazri", pos: "FW", club: "Montpellier", caps: 80, goals: 25, age: 35, number: 10 },
    ],
  },
  "Belgium": {
    name: "Belgium", code: "BEL", confederation: "UEFA", fifaRanking: 6,
    wcAppearances: 15, bestFinish: "Semi-finals (2018)", coach: "Domenico Tedesco",
    nickname: "Red Devils", kitColors: { primary: "#ED2939", secondary: "#000000" },
    history: "Belgium's golden generation — Hazard, De Bruyne, Lukaku, Courtois — peaked with a third-place finish in 2018. While that generation is aging out, De Bruyne remains world-class, and a new wave of talent ensures Belgium remain among the world's best.",
    squad: [
      { name: "Thibaut Courtois", pos: "GK", club: "Real Madrid", caps: 105, goals: 0, age: 34, number: 1 },
      { name: "Timothy Castagne", pos: "DF", club: "Fulham", caps: 40, goals: 2, age: 30, number: 21 },
      { name: "Kevin De Bruyne", pos: "MF", club: "Manchester City", caps: 105, goals: 27, age: 35, number: 7 },
      { name: "Youri Tielemans", pos: "MF", club: "Aston Villa", caps: 70, goals: 10, age: 29, number: 8 },
      { name: "Jérémy Doku", pos: "FW", club: "Manchester City", caps: 30, goals: 4, age: 24, number: 11 },
      { name: "Romelu Lukaku", pos: "FW", club: "Roma", caps: 115, goals: 85, age: 33, number: 9 },
    ],
  },
  "Egypt": {
    name: "Egypt", code: "EGY", confederation: "CAF", fifaRanking: 34,
    wcAppearances: 4, bestFinish: "Group stage (1934, 1990, 2018)", coach: "Hossam Hassan",
    nickname: "Pharaohs", kitColors: { primary: "#CE1126", secondary: "#FFFFFF" },
    history: "Egypt are Africa's most successful national team with seven AFCON titles. Mohamed Salah is the talisman of a squad that reached the 2017 and 2021 AFCON finals. Their 2018 World Cup return after 28 years was followed by disappointment, but they come back hungrier this time.",
    squad: [
      { name: "Mohamed El-Shennawy", pos: "GK", club: "Al Ahly", caps: 30, goals: 0, age: 35, number: 1 },
      { name: "Ahmed Hegazy", pos: "DF", club: "Al-Ittihad", caps: 70, goals: 4, age: 35, number: 6 },
      { name: "Mohamed Elneny", pos: "MF", club: "Beşiktaş", caps: 95, goals: 1, age: 34, number: 17 },
      { name: "Omar Marmoush", pos: "FW", club: "Manchester City", caps: 25, goals: 8, age: 27, number: 7 },
      { name: "Mohamed Salah", pos: "FW", club: "Liverpool", caps: 95, goals: 55, age: 34, number: 10 },
    ],
  },
  "Iran": {
    name: "Iran", code: "IRN", confederation: "AFC", fifaRanking: 21,
    wcAppearances: 7, bestFinish: "Group stage (1978–2022)", coach: "Amir Ghalenoei",
    nickname: "Team Melli", kitColors: { primary: "#FFFFFF", secondary: "#DA0000" },
    history: "Iran are Asia's most frequent World Cup qualifiers and have come agonizingly close to advancing — a last-minute equalizer denied them in 2014, and they nearly beat Portugal in 2018. They bring one of Asia's best defenses and a passionate diaspora fanbase.",
    squad: [
      { name: "Alireza Beiranvand", pos: "GK", club: "Persepolis", caps: 50, goals: 0, age: 34, number: 1 },
      { name: "Ehsan Hajsafi", pos: "DF", club: "AEK Athens", caps: 130, goals: 5, age: 36, number: 3 },
      { name: "Saeid Ezatolahi", pos: "MF", club: "Vejle", caps: 40, goals: 2, age: 29, number: 6 },
      { name: "Mehdi Taremi", pos: "FW", club: "Inter Milan", caps: 80, goals: 45, age: 34, number: 9 },
      { name: "Sardar Azmoun", pos: "FW", club: "Roma", caps: 75, goals: 45, age: 31, number: 20 },
    ],
  },
  "New Zealand": {
    name: "New Zealand", code: "NZL", confederation: "OFC", fifaRanking: 93,
    wcAppearances: 3, bestFinish: "Group stage (1982, 2010)", coach: "Darren Bazeley",
    nickname: "All Whites", kitColors: { primary: "#FFFFFF", secondary: "#000000" },
    history: "New Zealand famously went unbeaten at the 2010 World Cup with three draws, including against Italy. They are the dominant force in Oceanian football and return to the World Cup for the first time since 2010. Chris Wood leads their attack with Premier League pedigree.",
    squad: [
      { name: "Stefan Marinovic", pos: "GK", club: "Wellington Phoenix", caps: 30, goals: 0, age: 35, number: 1 },
      { name: "Liberato Cacace", pos: "DF", club: "Empoli", caps: 25, goals: 1, age: 25, number: 3 },
      { name: "Joe Bell", pos: "MF", club: "Brøndby", caps: 20, goals: 2, age: 25, number: 8 },
      { name: "Chris Wood", pos: "FW", club: "Nottingham Forest", caps: 70, goals: 35, age: 34, number: 9 },
    ],
  },
  "Spain": {
    name: "Spain", code: "ESP", confederation: "UEFA", fifaRanking: 3,
    wcAppearances: 17, bestFinish: "Champions (2010)", coach: "Luis de la Fuente",
    nickname: "La Roja", kitColors: { primary: "#AA151B", secondary: "#F1BF00" },
    history: "Spain won the 2010 World Cup and dominated 2008–2012 with tiki-taka. After a rebuild, they won Euro 2024 with a dazzling young squad. Lamine Yamal, 17, and Nico Williams represent perhaps the most exciting young attacking talent in world football. Spain arrive as one of the favorites.",
    squad: [
      { name: "Unai Simón", pos: "GK", club: "Athletic Bilbao", caps: 40, goals: 0, age: 29, number: 23 },
      { name: "Dani Carvajal", pos: "DF", club: "Real Madrid", caps: 50, goals: 4, age: 34, number: 2 },
      { name: "Rodri", pos: "MF", club: "Manchester City", caps: 60, goals: 5, age: 30, number: 16 },
      { name: "Pedri", pos: "MF", club: "Barcelona", caps: 35, goals: 3, age: 23, number: 8 },
      { name: "Lamine Yamal", pos: "FW", club: "Barcelona", caps: 20, goals: 5, age: 18, number: 19 },
      { name: "Nico Williams", pos: "FW", club: "Athletic Bilbao", caps: 25, goals: 6, age: 24, number: 11 },
      { name: "Álvaro Morata", pos: "FW", club: "AC Milan", caps: 80, goals: 36, age: 33, number: 7 },
    ],
  },
  "Cape Verde": {
    name: "Cape Verde", code: "CPV", confederation: "CAF", fifaRanking: 68,
    wcAppearances: 1, bestFinish: "Debut (2026)", coach: "Bubista",
    nickname: "Blue Sharks", kitColors: { primary: "#003893", secondary: "#CF2027" },
    history: "Cape Verde — a tiny Atlantic archipelago of half a million people — make their World Cup debut. Like Curaçao, they benefit from a diaspora that produces talent in European leagues. Their qualification is one of the greatest underdog stories in World Cup history.",
    squad: [
      { name: "Vozinha", pos: "GK", club: "Gil Vicente", caps: 45, goals: 0, age: 37, number: 1 },
      { name: "Steven Fortes", pos: "DF", club: "Estoril", caps: 35, goals: 2, age: 32, number: 2 },
      { name: "Nuno Borges", pos: "MF", club: "Arouca", caps: 25, goals: 3, age: 28, number: 8 },
      { name: "Garry Rodrigues", pos: "FW", club: "Olympiacos", caps: 50, goals: 10, age: 32, number: 7 },
    ],
  },
  "Saudi Arabia": {
    name: "Saudi Arabia", code: "KSA", confederation: "AFC", fifaRanking: 52,
    wcAppearances: 7, bestFinish: "Round of 16 (1994)", coach: "Roberto Mancini",
    nickname: "Green Falcons", kitColors: { primary: "#006C35", secondary: "#FFFFFF" },
    history: "Saudi Arabia produced the 2022 World Cup's biggest shock by beating Argentina 2-1 in the group stage, declared a national holiday. Under Mancini, the Saudi Pro League's investment in talent development aims to make them regulars among the world's elite.",
    squad: [
      { name: "Mohammed Al-Owais", pos: "GK", club: "Al-Hilal", caps: 60, goals: 0, age: 32, number: 1 },
      { name: "Ali Al-Bulaihi", pos: "DF", club: "Al-Hilal", caps: 50, goals: 1, age: 37, number: 12 },
      { name: "Salem Al-Dawsari", pos: "FW", club: "Al-Hilal", caps: 80, goals: 20, age: 33, number: 10 },
      { name: "Firas Al-Buraikan", pos: "FW", club: "Al-Ahli", caps: 30, goals: 12, age: 26, number: 7 },
    ],
  },
  "Uruguay": {
    name: "Uruguay", code: "URU", confederation: "CONMEBOL", fifaRanking: 10,
    wcAppearances: 14, bestFinish: "Champions (1930, 1950)", coach: "Marcelo Bielsa",
    nickname: "La Celeste", kitColors: { primary: "#75AADB", secondary: "#FFFFFF" },
    history: "Uruguay won the first World Cup in 1930 and pulled off the 'Maracanazo' in 1950 — beating Brazil in their own back yard. Under Bielsa, they reached the 2024 Copa América semi-finals with a fearless, pressing style. Darwin Núñez and Federico Valverde lead a potent squad.",
    squad: [
      { name: "Sergio Rochet", pos: "GK", club: "Inter Miami", caps: 25, goals: 0, age: 33, number: 1 },
      { name: "José Giménez", pos: "DF", club: "Atlético Madrid", caps: 80, goals: 5, age: 31, number: 2 },
      { name: "Ronald Araújo", pos: "DF", club: "Barcelona", caps: 25, goals: 2, age: 27, number: 4 },
      { name: "Federico Valverde", pos: "MF", club: "Real Madrid", caps: 60, goals: 8, age: 28, number: 15 },
      { name: "Darwin Núñez", pos: "FW", club: "Liverpool", caps: 40, goals: 10, age: 27, number: 11 },
      { name: "Luis Suárez", pos: "FW", club: "Inter Miami", caps: 140, goals: 68, age: 39, number: 9 },
    ],
  },
  "France": {
    name: "France", code: "FRA", confederation: "UEFA", fifaRanking: 2,
    wcAppearances: 17, bestFinish: "Champions (1998, 2018)", coach: "Didier Deschamps",
    nickname: "Les Bleus", kitColors: { primary: "#002395", secondary: "#FFFFFF" },
    history: "Two-time champions France are arguably the most talented squad in world football. Runner-up in 2022 after Mbappé's hat-trick heroics in the final, they remain hungry. The depth of French football — from Mbappé to Tchouaméni — is unmatched. Deschamps has built a winning machine.",
    squad: [
      { name: "Mike Maignan", pos: "GK", club: "AC Milan", caps: 20, goals: 0, age: 31, number: 16 },
      { name: "Theo Hernández", pos: "DF", club: "AC Milan", caps: 35, goals: 3, age: 28, number: 22 },
      { name: "William Saliba", pos: "DF", club: "Arsenal", caps: 25, goals: 1, age: 25, number: 17 },
      { name: "Aurélien Tchouaméni", pos: "MF", club: "Real Madrid", caps: 40, goals: 4, age: 26, number: 8 },
      { name: "Bradley Barcola", pos: "FW", club: "Paris Saint-Germain", caps: 15, goals: 5, age: 22, number: 7 },
      { name: "Kylian Mbappé", pos: "FW", club: "Real Madrid", caps: 85, goals: 48, age: 27, number: 10 },
    ],
  },
  "Senegal": {
    name: "Senegal", code: "SEN", confederation: "CAF", fifaRanking: 17,
    wcAppearances: 4, bestFinish: "Quarter-finals (2002)", coach: "Aliou Cissé",
    nickname: "Lions of Teranga", kitColors: { primary: "#FFFFFF", secondary: "#00853F" },
    history: "Senegal stunned France in the 2002 World Cup opener and reached the quarter-finals on debut. They won their first AFCON in 2022 behind Sadio Mané. Aliou Cissé, captain in 2002, coaches the current side. They've become Africa's most consistent top team.",
    squad: [
      { name: "Édouard Mendy", pos: "GK", club: "Al-Ahli", caps: 30, goals: 0, age: 34, number: 16 },
      { name: "Kalidou Koulibaly", pos: "DF", club: "Al-Hilal", caps: 70, goals: 3, age: 35, number: 3 },
      { name: "Idrissa Gueye", pos: "MF", club: "Everton", caps: 100, goals: 4, age: 36, number: 5 },
      { name: "Ismaïla Sarr", pos: "FW", club: "Crystal Palace", caps: 60, goals: 14, age: 28, number: 18 },
      { name: "Sadio Mané", pos: "FW", club: "Al-Nassr", caps: 100, goals: 40, age: 34, number: 10 },
    ],
  },
  "Iraq": {
    name: "Iraq", code: "IRQ", confederation: "AFC", fifaRanking: 62,
    wcAppearances: 2, bestFinish: "Group stage (1986)", coach: "Jesús Casas",
    nickname: "Lions of Mesopotamia", kitColors: { primary: "#FFFFFF", secondary: "#007A3D" },
    history: "Iraq's 2007 Asian Cup triumph — won during active conflict at home — remains one of football's most emotional achievements. They return to the World Cup for the first time since 1986, a testament to the resilience of Iraqi football through decades of adversity.",
    squad: [
      { name: "Jalal Hassan", pos: "GK", club: "Al-Shorta", caps: 40, goals: 0, age: 34, number: 1 },
      { name: "Ali Adnan", pos: "DF", club: "Al-Duhail", caps: 60, goals: 5, age: 32, number: 3 },
      { name: "Amjad Attwan", pos: "MF", club: "Al-Quwa Al-Jawiya", caps: 25, goals: 3, age: 26, number: 10 },
      { name: "Aymen Hussein", pos: "FW", club: "Al-Quwa Al-Jawiya", caps: 40, goals: 20, age: 30, number: 9 },
    ],
  },
  "Norway": {
    name: "Norway", code: "NOR", confederation: "UEFA", fifaRanking: 44,
    wcAppearances: 4, bestFinish: "Round of 16 (1998)", coach: "Ståle Solbakken",
    nickname: "Drillo's Boys / Norsemen", kitColors: { primary: "#BA0C2F", secondary: "#FFFFFF" },
    history: "Norway last appeared at the 1998 World Cup where they beat Brazil in the group stage. Now, with Erling Haaland — arguably the world's best striker — and Martin Ødegaard pulling the strings, they return as a genuine threat. This squad has the star power to go deep.",
    squad: [
      { name: "Ørjan Nyland", pos: "GK", club: "Sevilla", caps: 45, goals: 0, age: 35, number: 12 },
      { name: "Kristoffer Ajer", pos: "DF", club: "Brentford", caps: 35, goals: 1, age: 28, number: 3 },
      { name: "Martin Ødegaard", pos: "MF", club: "Arsenal", caps: 60, goals: 8, age: 27, number: 10 },
      { name: "Sander Berge", pos: "MF", club: "Fulham", caps: 45, goals: 4, age: 28, number: 8 },
      { name: "Erling Haaland", pos: "FW", club: "Manchester City", caps: 35, goals: 32, age: 25, number: 9 },
    ],
  },
  "Argentina": {
    name: "Argentina", code: "ARG", confederation: "CONMEBOL", fifaRanking: 1,
    wcAppearances: 19, bestFinish: "Champions (1978, 1986, 2022)", coach: "Lionel Scaloni",
    nickname: "La Albiceleste", kitColors: { primary: "#75AADB", secondary: "#FFFFFF" },
    history: "Reigning World Cup champions after Messi's 2022 triumph in Qatar — the fairytale ending to the greatest career in football. With Messi likely playing his final World Cup at 39, Argentina will be driven by emotion and an exceptional squad depth that also won the 2024 Copa América.",
    squad: [
      { name: "Emiliano Martínez", pos: "GK", club: "Aston Villa", caps: 50, goals: 0, age: 33, number: 23 },
      { name: "Cristian Romero", pos: "DF", club: "Tottenham", caps: 30, goals: 2, age: 28, number: 13 },
      { name: "Rodrigo De Paul", pos: "MF", club: "Atlético Madrid", caps: 60, goals: 4, age: 32, number: 7 },
      { name: "Enzo Fernández", pos: "MF", club: "Chelsea", caps: 30, goals: 3, age: 25, number: 24 },
      { name: "Lionel Messi", pos: "FW", club: "Inter Miami", caps: 185, goals: 109, age: 39, number: 10 },
      { name: "Julián Álvarez", pos: "FW", club: "Atlético Madrid", caps: 30, goals: 10, age: 26, number: 9 },
      { name: "Lautaro Martínez", pos: "FW", club: "Inter Milan", caps: 55, goals: 25, age: 28, number: 22 },
    ],
  },
  "Algeria": {
    name: "Algeria", code: "ALG", confederation: "CAF", fifaRanking: 31,
    wcAppearances: 5, bestFinish: "Round of 16 (2014)", coach: "Vladimir Petković",
    nickname: "Desert Foxes", kitColors: { primary: "#FFFFFF", secondary: "#006233" },
    history: "Algeria won the 2019 AFCON in style, led by Riyad Mahrez. They reached the 2014 World Cup Round of 16, pushing eventual champions Germany to extra time. Their passionate fanbase and skilful attack make them one of Africa's strongest sides.",
    squad: [
      { name: "Raïs M'Bolhi", pos: "GK", club: "ES Sétif", caps: 90, goals: 0, age: 38, number: 23 },
      { name: "Aïssa Mandi", pos: "DF", club: "Villarreal", caps: 75, goals: 3, age: 34, number: 6 },
      { name: "Ismaël Bennacer", pos: "MF", club: "AC Milan", caps: 50, goals: 2, age: 28, number: 8 },
      { name: "Riyad Mahrez", pos: "FW", club: "Al-Ahli", caps: 85, goals: 30, age: 35, number: 7 },
      { name: "Islam Slimani", pos: "FW", club: "Coritiba", caps: 90, goals: 45, age: 38, number: 13 },
    ],
  },
  "Austria": {
    name: "Austria", code: "AUT", confederation: "UEFA", fifaRanking: 22,
    wcAppearances: 8, bestFinish: "Semi-finals (1954)", coach: "Ralf Rangnick",
    nickname: "Das Team", kitColors: { primary: "#ED2939", secondary: "#FFFFFF" },
    history: "Austria punched above their weight at Euro 2024 under Ralf Rangnick, topping a group containing France and the Netherlands. Rangnick's intense pressing system has transformed them from consistent underachievers into a genuinely dangerous side. They return to the World Cup for the first time since 1998.",
    squad: [
      { name: "Patrick Pentz", pos: "GK", club: "Brøndby", caps: 15, goals: 0, age: 29, number: 1 },
      { name: "David Alaba", pos: "DF", club: "Real Madrid", caps: 105, goals: 15, age: 34, number: 8 },
      { name: "Konrad Laimer", pos: "MF", club: "Bayern Munich", caps: 35, goals: 2, age: 29, number: 14 },
      { name: "Marcel Sabitzer", pos: "MF", club: "Borussia Dortmund", caps: 75, goals: 15, age: 32, number: 9 },
      { name: "Christoph Baumgartner", pos: "FW", club: "RB Leipzig", caps: 40, goals: 14, age: 27, number: 19 },
    ],
  },
  "Jordan": {
    name: "Jordan", code: "JOR", confederation: "AFC", fifaRanking: 67,
    wcAppearances: 1, bestFinish: "Debut (2026)", coach: "Hussein Ammouta",
    nickname: "Al-Nashama", kitColors: { primary: "#FFFFFF", secondary: "#007A3D" },
    history: "Jordan make their World Cup debut after reaching the 2023 Asian Cup final, where they lost to Qatar. It was a stunning run that captured the Arab world's imagination. Their qualification is a historic moment for Jordanian football and a reward for years of steady development.",
    squad: [
      { name: "Yazeed Abulaila", pos: "GK", club: "Al-Faisaly", caps: 30, goals: 0, age: 28, number: 1 },
      { name: "Anas Bani Yaseen", pos: "DF", club: "Al-Faisaly", caps: 50, goals: 4, age: 32, number: 5 },
      { name: "Mousa Al-Taamari", pos: "MF", club: "Montpellier", caps: 45, goals: 10, age: 28, number: 7 },
      { name: "Yazan Al-Naimat", pos: "FW", club: "Gent", caps: 20, goals: 8, age: 25, number: 9 },
    ],
  },
  "Portugal": {
    name: "Portugal", code: "POR", confederation: "UEFA", fifaRanking: 5,
    wcAppearances: 9, bestFinish: "Semi-finals (1966, 2006)", coach: "Roberto Martínez",
    nickname: "A Seleção", kitColors: { primary: "#FF0000", secondary: "#006600" },
    history: "Euro 2016 champions Portugal boast arguably the deepest squad in world football. While Cristiano Ronaldo — likely at his last World Cup at 41 — remains the figurehead, the depth behind him is extraordinary: Bernardo Silva, Bruno Fernandes, Rafael Leão, João Félix.",
    squad: [
      { name: "Diogo Costa", pos: "GK", club: "Porto", caps: 20, goals: 0, age: 27, number: 1 },
      { name: "Rúben Dias", pos: "DF", club: "Manchester City", caps: 50, goals: 3, age: 29, number: 4 },
      { name: "Bernardo Silva", pos: "MF", club: "Manchester City", caps: 80, goals: 12, age: 31, number: 10 },
      { name: "Bruno Fernandes", pos: "MF", club: "Manchester United", caps: 70, goals: 22, age: 31, number: 8 },
      { name: "Rafael Leão", pos: "FW", club: "AC Milan", caps: 35, goals: 8, age: 27, number: 17 },
      { name: "Cristiano Ronaldo", pos: "FW", club: "Al-Nassr", caps: 210, goals: 130, age: 41, number: 7 },
    ],
  },
  "DR Congo": {
    name: "DR Congo", code: "COD", confederation: "CAF", fifaRanking: 50,
    wcAppearances: 2, bestFinish: "Group stage (1974 as Zaire)", coach: "Sébastien Desabre",
    nickname: "Leopards", kitColors: { primary: "#007FFF", secondary: "#CE1021" },
    history: "DR Congo (formerly Zaire) return to the World Cup for the first time since 1974. They reached the 2015 AFCON semi-finals and are a rising African force. The squad features several Europe-based players who bring pace and physicality to a team with a passionate fanbase.",
    squad: [
      { name: "Joël Kiassumbua", pos: "GK", club: "Yverdon", caps: 15, goals: 0, age: 27, number: 16 },
      { name: "Chancel Mbemba", pos: "DF", club: "Marseille", caps: 55, goals: 5, age: 31, number: 22 },
      { name: "Samuel Moutoussamy", pos: "MF", club: "Nantes", caps: 20, goals: 2, age: 28, number: 8 },
      { name: "Cédric Bakambu", pos: "FW", club: "Betis", caps: 45, goals: 15, age: 33, number: 9 },
      { name: "Silas Katompa", pos: "FW", club: "Stuttgart", caps: 15, goals: 4, age: 25, number: 7 },
    ],
  },
  "Uzbekistan": {
    name: "Uzbekistan", code: "UZB", confederation: "AFC", fifaRanking: 63,
    wcAppearances: 1, bestFinish: "Debut (2026)", coach: "Srecko Katanec",
    nickname: "White Wolves", kitColors: { primary: "#FFFFFF", secondary: "#1EB53A" },
    history: "Uzbekistan make their World Cup debut after years of near-misses in Asian qualification. They've been a consistent Asian Cup semi-finalist and runner-up. The White Wolves bring disciplined tactical play and a squad with growing international experience.",
    squad: [
      { name: "Eldor Suyunov", pos: "GK", club: "Lokomotiv Tashkent", caps: 20, goals: 0, age: 28, number: 1 },
      { name: "Abdukodir Khusanov", pos: "DF", club: "Manchester City", caps: 15, goals: 0, age: 21, number: 3 },
      { name: "Jaloliddin Masharipov", pos: "MF", club: "Al-Shabab", caps: 50, goals: 10, age: 33, number: 11 },
      { name: "Eldor Shomurodov", pos: "FW", club: "Roma", caps: 40, goals: 15, age: 29, number: 9 },
    ],
  },
  "Colombia": {
    name: "Colombia", code: "COL", confederation: "CONMEBOL", fifaRanking: 12,
    wcAppearances: 7, bestFinish: "Quarter-finals (2014)", coach: "Néstor Lorenzo",
    nickname: "Los Cafeteros", kitColors: { primary: "#FCD116", secondary: "#003893" },
    history: "Colombia reached the 2024 Copa América final and the 2014 World Cup quarter-finals behind James Rodríguez's Golden Boot. Luis Díaz and Rafael Santos Borré lead a flair-filled squad. Colombian football blends technical skill with South American passion.",
    squad: [
      { name: "Camilo Vargas", pos: "GK", club: "Atlas", caps: 35, goals: 0, age: 36, number: 1 },
      { name: "Davinson Sánchez", pos: "DF", club: "Galatasaray", caps: 60, goals: 3, age: 30, number: 23 },
      { name: "James Rodríguez", pos: "MF", club: "León", caps: 105, goals: 26, age: 34, number: 10 },
      { name: "Jhon Arias", pos: "FW", club: "Zenit", caps: 20, goals: 3, age: 27, number: 21 },
      { name: "Luis Díaz", pos: "FW", club: "Liverpool", caps: 45, goals: 10, age: 29, number: 7 },
      { name: "Rafael Santos Borré", pos: "FW", club: "Internacional", caps: 25, goals: 5, age: 30, number: 19 },
    ],
  },
  "England": {
    name: "England", code: "ENG", confederation: "UEFA", fifaRanking: 4,
    wcAppearances: 17, bestFinish: "Champions (1966)", coach: "Thomas Tuchel",
    nickname: "Three Lions", kitColors: { primary: "#FFFFFF", secondary: "#002366" },
    history: "England won the 1966 World Cup at Wembley and have endured decades of heartbreak since — penalty shootout eliminations became a national trauma. Under Southgate, they reached two Euro finals and the 2018 World Cup semi-final. Now under Tuchel, they have the squad to go all the way.",
    squad: [
      { name: "Jordan Pickford", pos: "GK", club: "Everton", caps: 65, goals: 0, age: 32, number: 1 },
      { name: "Trent Alexander-Arnold", pos: "DF", club: "Liverpool", caps: 30, goals: 3, age: 27, number: 66 },
      { name: "Declan Rice", pos: "MF", club: "Arsenal", caps: 60, goals: 5, age: 27, number: 4 },
      { name: "Jude Bellingham", pos: "MF", club: "Real Madrid", caps: 45, goals: 8, age: 23, number: 10 },
      { name: "Bukayo Saka", pos: "FW", club: "Arsenal", caps: 50, goals: 15, age: 24, number: 7 },
      { name: "Harry Kane", pos: "FW", club: "Bayern Munich", caps: 100, goals: 68, age: 32, number: 9 },
      { name: "Phil Foden", pos: "FW", club: "Manchester City", caps: 40, goals: 6, age: 26, number: 47 },
    ],
  },
  "Croatia": {
    name: "Croatia", code: "CRO", confederation: "UEFA", fifaRanking: 9,
    wcAppearances: 7, bestFinish: "Runner-up (2018)", coach: "Zlatko Dalić",
    nickname: "Vatreni (The Blazers)", kitColors: { primary: "#FF0000", secondary: "#FFFFFF" },
    history: "Croatia reached the 2018 World Cup final and finished third in 2022 — remarkable for a nation of four million. Luka Modrić, one of the greatest midfielders ever, will likely make his final World Cup bow. Croatia consistently punch far above their weight on the global stage.",
    squad: [
      { name: "Dominik Livaković", pos: "GK", club: "Fenerbahçe", caps: 50, goals: 0, age: 31, number: 1 },
      { name: "Joško Gvardiol", pos: "DF", club: "Manchester City", caps: 40, goals: 3, age: 24, number: 20 },
      { name: "Luka Modrić", pos: "MF", club: "Real Madrid", caps: 175, goals: 24, age: 40, number: 10 },
      { name: "Mateo Kovačić", pos: "MF", club: "Manchester City", caps: 95, goals: 5, age: 32, number: 8 },
      { name: "Andrej Kramarić", pos: "FW", club: "Hoffenheim", caps: 80, goals: 28, age: 34, number: 9 },
    ],
  },
  "Ghana": {
    name: "Ghana", code: "GHA", confederation: "CAF", fifaRanking: 45,
    wcAppearances: 5, bestFinish: "Quarter-finals (2010)", coach: "Otto Addo",
    nickname: "Black Stars", kitColors: { primary: "#FFFFFF", secondary: "#006B3F" },
    history: "Ghana became the third African team to reach the World Cup quarter-finals in 2010, only missing the semi-finals due to Suárez's infamous handball. Asamoah Gyan's penalty miss remains one of football's most painful moments. A new generation seeks to finally break the ceiling.",
    squad: [
      { name: "Lawrence Ati-Zigi", pos: "GK", club: "St. Gallen", caps: 15, goals: 0, age: 28, number: 1 },
      { name: "Mohammed Salisu", pos: "DF", club: "AS Monaco", caps: 20, goals: 1, age: 27, number: 4 },
      { name: "Thomas Partey", pos: "MF", club: "Free Agent", caps: 50, goals: 14, age: 33, number: 5 },
      { name: "Mohammed Kudus", pos: "FW", club: "West Ham", caps: 30, goals: 8, age: 26, number: 10 },
      { name: "Iñaki Williams", pos: "FW", club: "Athletic Bilbao", caps: 20, goals: 3, age: 32, number: 9 },
    ],
  },
  "Panama": {
    name: "Panama", code: "PAN", confederation: "CONCACAF", fifaRanking: 64,
    wcAppearances: 2, bestFinish: "Group stage (2018)", coach: "Thomas Christiansen",
    nickname: "Los Canaleros", kitColors: { primary: "#DA291C", secondary: "#003893" },
    history: "Panama's 2018 World Cup debut was a nation-defining moment — a national holiday was declared when they qualified. Their first World Cup goal, scored by Felipe Baloy against England, brought tears to a nation. They return more experienced and determined to make a deeper run.",
    squad: [
      { name: "Luis Mejía", pos: "GK", club: "Leganés", caps: 35, goals: 0, age: 32, number: 1 },
      { name: "Fidel Escobar", pos: "DF", club: "Saprissa", caps: 45, goals: 2, age: 31, number: 4 },
      { name: "Adalberto Carrasquilla", pos: "MF", club: "Houston Dynamo", caps: 40, goals: 4, age: 28, number: 8 },
      { name: "José Fajardo", pos: "FW", club: "Saprissa", caps: 30, goals: 10, age: 28, number: 11 },
    ],
  },
};
